#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # create system user required to run the openvpn daemon unprivileged
    adduser --quiet --system \
            --home /var/lib/openvpn/chroot \
            --gecos "NetworkManager OpenVPN" \
            --group nm-openvpn

    # remove existing tmp directory to prevent nm-openvpn to run in a chroot
    if [ -d /var/lib/openvpn/chroot/tmp ]; then
        rmdir --ignore-fail-on-non-empty /var/lib/openvpn/chroot/tmp
    fi
fi

#DEBHELPER#
